### ISSUE TITLE
Overflow dropdown styling is not Carbon compliant 

### ISSUE THREAD

**Issue by nabilIbm** [elyra-ai/canvas#1061]
Ref : 3014

-Incorrect drop shadow
-Dropdown doesnt connect to overflow icon, which is also not persistent
-Text color should be grey
-Improper spacing on text
-Background should be grey, not white

...and likely other visual defects. Basically the Carbon dropdown is not being used here:
https://react.carbondesignsystem.com/?path=/story/overflowmenu--basic

 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/89609176/169888476-63d1f4b0-968b-43e7-940c-afadd917dfd8.png">

**Comment by tomlyn** [comment]
This working has halted so I'm closing this issues for now. Will reopen when work resumes.
