### ISSUE TITLE
Build broken for test harness: recat dependencies unresolvable

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/canvas#1132]
Followed the [documentation](https://github.com/elyra-ai/canvas/tree/main/canvas_modules/harness) to build the test harness but on *npm install* in /home/ubuntu/canvas/canvas_modules/harness I get:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: canvas-demo@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   dev react@"16.13.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.0-rc.2" from @hot-loader/react-dom@17.0.0-rc.2
npm ERR! node_modules/@hot-loader/react-dom
npm ERR!   dev @hot-loader/react-dom@"17.0.0-rc.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ubuntu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-07-27T10_36_12_001Z-debug.log
`
`

When bumping react from 16.13.1 to 17.0.0-rc.2 in package.json, I get:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: canvas-demo@0.0.1
npm ERR! Found: react@17.0.0-rc.2
npm ERR! node_modules/react
npm ERR!   dev react@"17.0.0-rc.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16" from @carbon/icons-react@10.49.0
npm ERR! node_modules/@carbon/icons-react
npm ERR!   dev @carbon/icons-react@"10.49.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ubuntu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-07-27T10_30_26_399Z-debug.log
`
`

So I'd say carbon is pinning react to <= v16, correct?

**Comment by nmgokhale** [comment]
@romeokienzler What is the node version? These errors are usually seen in node 16.x.
Elyra-canvas uses node 14.x

**Comment by romeokienzler** [comment]
@nmgokhale 18.7.0 ;) thanks a lot! Will send an update tomorrow

**Comment by EMCP** [comment]
@nmgokhale , I can see this even with nodejs 14.20.0 LTS

```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @elyra/canvas@12.6.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16" from @carbon/icons-react@10.43.0
npm ERR!   node_modules/@carbon/icons-react
npm ERR!     @carbon/icons-react@"10.43.0" from @elyra/canvas@12.6.0
npm ERR!     node_modules/@elyra/canvas
npm ERR!       @elyra/canvas@"^12.6.0" from the root project
npm ERR!     @carbon/icons-react@"^10.43.0" from carbon-components-react@7.48.0
npm ERR!     node_modules/carbon-components-react
npm ERR!       carbon-components-react@"^7.48.0" from the root project
npm ERR!       1 more (@elyra/canvas)
npm ERR!   15 more (@testing-library/react, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from @elyra/canvas@12.6.0
npm ERR! node_modules/@elyra/canvas
npm ERR!   @elyra/canvas@"^12.6.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.0.0" from @elyra/canvas@12.6.0
npm ERR!   node_modules/@elyra/canvas
npm ERR!     @elyra/canvas@"^12.6.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/emcp/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emcp/.npm/_logs/2022-07-28T20_48_45_775Z-debug-0.log

```

**Comment by EMCP** [comment]
I can confirm, this is broken on nodejs 16.. backing off to v14 seems to repair things.. any idea on a timeline for support ?

**Comment by nmgokhale** [comment]
`npm install` works fine for me on node version 14.20.0.

I will open a issue to upgrade to node 16.x. Until then, temporary workaround is running - `npm install --legacy-peer-deps`.

**Comment by romeokienzler** [comment]
Thanks a lot @nmgokhale, downgrading to Node v14.x works fine for me

![image](https://user-images.githubusercontent.com/5694071/181742589-a45946fd-eae9-4a73-8d7c-d41909aec3c5.png)
