### ISSUE TITLE
Palette should have open/close animation

### ISSUE THREAD

**Issue by matthoward366** [elyra-ai/canvas#1484]
Currently the palette opens/closed immediately but should have some animation.  Most likely productive from
https://v10.carbondesignsystem.com/guidelines/motion/overview/

**Comment by tomlyn** [comment]
Not sure when it as implemented but the palette opening and closing is now animated

https://github.com/user-attachments/assets/658f74cb-bbc5-4b44-89ab-fe36fec2a60e
