### ISSUE TITLE
Node context toolbar broken in Firefox ESR (@elyra/canvas 12.32.0)

### ISSUE THREAD

**Issue by EAlexRojas** [elyra-ai/canvas#1530]
Ref 3581

When using `@elyra/canvas` 12.32.0 and activating the `enableContextToolbar` config option, if you try to hover a node to show the toolbar options, the app crashes on Firefox ESR (102.13.0) with the error:

` Uncaught TypeError: e19.findLastIndex is not a function`

<img width="800" alt="Screenshot 2023-07-20 at 15 02 28" src="https://github.com/elyra-ai/canvas/assets/2373303/63fd6ffe-55a5-492d-a6f5-e24b07c063f8">

I seems to be caused by the commit: https://github.com/elyra-ai/canvas/commit/9659a8cad6f52cbe4a4d9d4a79aec8297ff43be7#diff-2f25a37525dc481b91cf9c9739fdf45b57a62ebf27bca9937920f95510cdbd1bR122

The method `findLastIndex` is not supported by FirefoxESR currently.
Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex

**Comment by matthoward366** [comment]
@caritaou Is this something you could have a look at or do we need to wait for @tomlyn?

**Comment by caritaou** [comment]
@EAlexRojas Do you have an eta of when you need the fix? Is this high priority? Also, are you able to share which product/application this is for? Thanks!

**Comment by EAlexRojas** [comment]
Hi @caritaou,
This is for IBM Event Automation. It's not urgent, we can for now use the version [12.31.2](https://github.com/elyra-ai/canvas/releases/tag/release_12.31.2).
But it would be needed if we want to use latest version in next releases.

**Comment by tomlyn** [comment]
@EAlexRojas Which FF ESR version are you using? It looks like the latest is [115.0.3esr](https://www.mozilla.org/en-US/firefox/115.0.3esr/releasenotes/). Although I don't have it installed, I would think it would have the required support for `findLastIndex`. It only came out a few days ago so maybe that was after you opened this issue.

@caritaou I created this PR if Alex wants a fix after trying the latest ESR:  https://github.com/elyra-ai/canvas/pull/1536
You'll see I changed the publish script so you can build a patch release if that is needed.

**Comment by EAlexRojas** [comment]
As I stated in the issue description I was using Firefox ESR 102.13.0, the 115 version was not available at the time.

I just upgraded the version locally to 115, tested again and I don't reproduce the issue in that version of Firefox ESR.

**Comment by caritaou** [comment]
Thanks for checking @EAlexRojas, since it works in the latest version, is this fix still required? Or okay to close?

**Comment by EAlexRojas** [comment]
I checked and for our product we claim compatibility with Firefox version 113 or later, so it should be OK for us.

Not sure if it would be the case for all consumers of elyra canvas, I'll let you decide wether to close the issue with the fix or without it.

Thanks.
