### ISSUE TITLE
Consider adding React 17 support to `@elyra/canvas`?

### ISSUE THREAD

**Issue by s100** [elyra-ai/canvas#1559]
Ref: 3597

Hello there. We are currently using React 16 and we are attempting to upgrade to React 17. We aren't able to upgrade to React 18 yet, because we have various other dependencies which don't support it, and a very large number of tests which we need to rewrite - we're using [Enzyme](https://enzymejs.github.io/enzyme/), which is [dead](https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl), with no support for React 18 and only sketchy support for React 17.

Would you consider adding React 17 to the version specifiers here?

https://github.com/elyra-ai/canvas/blob/4fe5077408aea11b60ca5d1ff48af44d2ff79fe8/canvas_modules/common-canvas/package.json#L108-L109

I can open the PR if that would be helpful - it looks like it would be fairly simple to do. Thank you.

**Comment by tomlyn** [comment]
Hi @s100 -- Thanks for opening this. We hope to get this fixed in the next release.  
Are you an IBMer? Someone recently asked for that exact same change on the internal #elyra-canvas channel - was that you?

**Comment by s100** [comment]
That wasn't me but yes, I am an IBMer. It's possible that was one of my colleagues.

> We hope to get this fixed in the next release.

👍

**Comment by s100** [comment]
@tomlyn Thank you for the prompt fix. Will there be a new release of `@elyra/canvas` with this fix in it soon?

**Comment by s100** [comment]
Beautiful! Thank you very much!

**Comment by s100** [comment]
Incidentally, I'm noticing now that `@elyra/canvas`'s own dependencies `react-codemirror2`, `react-contextmenu` and `react-resize-detector` themselves do not appear to support React 17 or React 18. Not sure if this is going to cause us further problems, but it's something you should be aware of as this may affect `@elyra/canvas`'s own ability to support newer versions of React.
