### ISSUE TITLE
Add an option to refresh parameterDef for common-properties

### ISSUE THREAD

**Issue by nmgokhale** [elyra-ai/canvas#1575]
Ref: 3603

Add a new config option in [propertiesInfo object](https://github.com/elyra-ai/canvas/wiki/3.0-Common-Properties-documentation#step-2--set-the-data).

```
id:  "{id}"	            // Unique parameter definition ID [Optional]
```

`id` will be used to compare whether updated parameterDef is provided or a completely new parameterDef is provided to the common-properties.

In updated parameterDef, don't set `type: initial_load` on pre-existing properties.

**Comment by matthoward366** [comment]
Instead of a boolean maybe just a ID.  Then we compare the ids to see if they've changed.
