### ISSUE TITLE
Go to `react-redux@8` or declare it as a production dependency?

### ISSUE THREAD

**Issue by s100** [elyra-ai/canvas#1576]
This is a little complex to explain, so please bear with me. In our application, we use `react-redux@8`, and we are currently trying to also use `@elyra/canvas`, which has a peer dependency on `react-redux@7`:

https://github.com/elyra-ai/canvas/blob/7bf40a9850221f41e404d11a419041781b9b0503/canvas_modules/common-canvas/package.json#L111

In practice, I don't believe these clashing versions of `react-redux` should cause an issue, because the main `CommonCanvas` component is encapsulated with its own `<Provider>`:

https://github.com/elyra-ai/canvas/blob/7bf40a9850221f41e404d11a419041781b9b0503/canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx#L77-L79

However, this version conflict is still causing the following error for us at `npm install` time:

```
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @ibm-app-connect/ui-ace-sw@9.0.522
npm ERR! Found: react-redux@8.1.2
npm ERR! node_modules/react-redux
npm ERR!   dev react-redux@"^8.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-redux@"^7.0.0" from @elyra/canvas@12.34.0
npm ERR! node_modules/@elyra/canvas
npm ERR!   dev @elyra/canvas@"^12.34.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I believe that this issue could be resolved in one of two ways.

* One would be to declare `react-redux` as a *production* dependency of `@elyra/canvas`. It is actually used directly in production so I think this would be logical.
* Another would be for `@elyra/canvas` to upgrade from `react-redux@7` to `react-redux@8`. This upgrade was relatively painless for us when we did it, so I hope you would find the same. For your reference, [here are the release notes for `react-redux@8.0.0`](https://github.com/reduxjs/react-redux/releases/tag/v8.0.0).

In fact, ideally I think you should do both of these things.

---

OK so cards on the table, the above is a simplification of the real issue. We do not use `@elyra/canvas` directly, we use a package `@icp4i/cp4i-operand-create` which uses `@icp4i/cp4i-canvas` which uses `@elyra/canvas`. At `npm install` time, due to the conflict described above, npm does not install `@elyra/canvas` at the top level in `./node_modules/@elyra/canvas`. Instead it installs both `@elyra/canvas` and its dependency `react-redux@7` at a lower level, in `./node_modules/@icp4i/cp4i-canvas/node_modules/@elyra/canvas` and `./node_modules/@icp4i/cp4i-canvas/node_modules/react-redux` respectively.

Then, during the CSS phase of our webpack build, we attempt to pull in `@icp4i/cp4i-canvas`'s SCSS, which includes the line:

```scss
@import '@elyra/canvas/src/index';
```

This import is trying to find `@elyra/canvas` at the top level, in `./node_modules/@elyra/canvas`, but it fails, which then fails our build:

```
Error: Can't find stylesheet to import.
  ╷
1 │ @import '@elyra/canvas/src/index';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@icp4i\cp4i-canvas\es\client\globals.scss 1:9                   @use
  node_modules\@icp4i\cp4i-canvas\es\client\components\Canvas\Canvas.scss 1:1  root stylesheet
```

If `@elyra/canvas` were installed at the top level, this issue would go away.

Thank you!

**Comment by tomlyn** [comment]
This has been moved to internal tracking Ref: 3703

**Comment by s100** [comment]
@tomlyn Can you provide a link to the place where you're now tracking this issue? I'd like to be able to subscribe to updates so that I can know when it gets fixed.

**Comment by tomlyn** [comment]
@s100 I sent you a DM

**Comment by tomlyn** [comment]
@s100 This will be in the next release of Elyra Canvas v13

**Comment by s100** [comment]
@tomlyn When will that be?

**Comment by nmgokhale** [comment]
@s100 We will release next 13.x alpha version on Monday 4/8.

**Comment by s100** [comment]
Thank you. Looking forward to it. An alpha release is fine but I'm really looking for a production-ready version.

**Comment by nmgokhale** [comment]
@s100 This issue is fixed in version [13.0.0-alpha.1 ](https://github.com/elyra-ai/canvas/releases/tag/v13.0.0-alpha.1).

**Comment by s100** [comment]
@nmgokhale That's an alpha release. Is it ready for production use?

**Comment by s100** [comment]
`@elyra/canvas@13.0.0` has now been released but the `latest` tag still points at `@elyra/canvas@12.46.0` so it's still unclear whether V13 is ready for production use...

**Comment by tomlyn** [comment]
Hi s100 - Thanks for mentioning this. We are aware of this problem and have an issue to address it.  Be assured v13.0.0 is ready for production use.
