### ISSUE TITLE
nodeTemplate inputs and output ui_data is being deleted

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/canvas#162]
This was discovered in https://github.com/elyra-ai/elyra/issues/750 and a more detailed investigation is commented there.

When using the function [convertNodeTemplate ](https://github.com/elyra-ai/canvas/blob/3b42563c6e135a9d28d040596a87c541d1113bc3/canvas_modules/common-canvas/src/object-model/object-model.js#L176) on palette the function specifically calls out that `app_data` must be cloned so that the delete later in the function does not affect the nodeTemplate passed into the function but the new json instance being returned. But then later in the function [convertPort](https://github.com/elyra-ai/canvas/blob/3b42563c6e135a9d28d040596a87c541d1113bc3/canvas_modules/common-canvas/src/object-model/object-model.js#L212) is called on `inputs` and `output` which goes through a similar process with `ui_data` but this time without first cloning it, thus deleting it from the passed in nodeTemplate. This means that the `ui_data` for `inputs` and `outputs` are only used for the first node added to the canvas and no future node.

**Comment by tomlyn** [comment]
@ajbozarth Hi Alex -- thanks for opening this and for the investigation.  I've fixed it and pushed a change into master. It now clones he entire nodeTemplate and then does modifications on the clone so the palette nodeTemplate cannot get altered. 

We do a new build each Monday so it will be available in the NPM module then or, if you prefer, I can kick off a build now -- just let me know if you want that.

**Comment by ajbozarth** [comment]
No rush on the build, Elyra is actually still locked to version 6 for now, updating to use latest canvas is currently on our docket due to this and a handful of other fixes we need in new releases.

**Comment by tomlyn** [comment]
@ajbozarth OK. When you upgrade to v8 be sure to read through the release notes for previous releases some of which will be in the old wdp-abstract-canvas repo.  In particular these changes for 8.0.1 will almost certainly impact your code:
https://github.ibm.com/NGP-TWC/wdp-abstract-canvas/releases/tag/release-8.0.1

**Comment by ajbozarth** [comment]
cc @vabarbosa since he's looking into the update
