### ISSUE TITLE
 Migrate elyra-canvas documentation to Sphinx(Readthedocs)

### ISSUE THREAD

**Issue by caritaou** [elyra-ai/canvas#172]
Similar to what was done in Elyra https://github.com/elyra-ai/elyra/issues/428, we want to migrate the [wiki pages](https://github.com/elyra-ai/canvas/wiki) to use [readthedocs.](https://docs.readthedocs.io). 

We currently have 24 pages in the wiki that will need to be separated out into different sections. In the wiki, this is currently distinguished by the the titles. All the 2.x pages should be grouped together, the 3.x pages should be grouped together, and so on.

**Comment by tomlyn** [comment]
We went with Github pages instead, Closing this issue.
