### ISSUE TITLE
Update cypress tests to ignore decimal numbers for comparison

### ISSUE THREAD

**Issue by nmgokhale** [elyra-ai/canvas#176]
In Cypress tests, verification commands include px having decimal numbers.
Compare integer part of numbers (+ or - 1 px). 
<img width="884" alt="Screen Shot 2020-07-22 at 4 37 56 PM" src="https://user-images.githubusercontent.com/25124000/88239905-846b1080-cc3a-11ea-9a39-6899122696b2.png">

**Comment by tomlyn** [comment]
Let''s make the '1px' a single constant somewhere, so we can bump it up if we find a situation where it needs just a little bit more.
