### ISSUE TITLE
Fix Typo in Elyra docs.

### ISSUE THREAD

**Issue by srikant-ch5** [elyra-ai/canvas#1989]
In side menu fix below typo for `Command Stack`

<img width="723" alt="Screenshot 2024-05-28 at 12 34 41 PM" src="https://github.com/elyra-ai/canvas/assets/16302714/3a05be0d-061c-42b3-b752-c1c90cdda015">

**Comment by tomlyn** [comment]
@srikant Thanks for noticing this and fixing it.
