### ISSUE TITLE
Parallax sample app does not look good in dark mode

### ISSUE THREAD

**Issue by PRINCESANCHEZ** [elyra-ai/canvas#2105]
The parallax sample app in the test harness does not look nice in dark mode. 
ref: #2161

<img width="1136" alt="Screenshot 2024-08-12 at 8 56 30 PM" src="https://github.com/user-attachments/assets/9defac29-0241-4ccc-8933-9d96563fbb26">

**Comment by tomlyn** [comment]
FIxed
