### ISSUE TITLE
Palette search text highlight not good in Dark Mode

### ISSUE THREAD

**Issue by PRINCESANCHEZ** [elyra-ai/canvas#2125]
Desc: ref 3847
The highlight color token used for highlighting Search text in the palette looks good in Light mode

<img width="271" alt="image" src="https://media.github.ibm.com/user/1006/files/0e617316-e5bb-482e-9810-5103712045ee">

but not in Dark mode

<img width="263" alt="image" src="https://media.github.ibm.com/user/1006/files/91b9497a-018f-4222-8a9b-9580eccea9c1">

**Comment by tomlyn** [comment]
Fixed by Prince.
