### ISSUE TITLE
Upgrade to `react-redux@8`

### ISSUE THREAD

**Issue by s100** [elyra-ai/canvas#2180]
Ref: 3879

All the other package in our application use `react-redux@8`, which was released in April 2022. `However, `@elyra/canvas` is lagging behind on `react-redux@7`. Would you consider upgrading?

I asked about this previously under #1576. That issue was closed, but no version of `@elyra/canvas` was ever actually released with this fix in. The latest is `@elyra/canvas@13.9.1` which still uses `react-redux@7.2.8`, and is in fact pinned to that version.

https://github.com/elyra-ai/canvas/blob/cd14e088a5d7e73020c04cf8b01313ec8efde742/canvas_modules/common-canvas/package.json#L48

**Comment by tomlyn** [comment]
Implemented in Elyra Canvas v13.10.0
