### ISSUE TITLE
[SDG] Differential privacy ux issues - Fix font type for properties label

### ISSUE THREAD

**Issue by veenas1** [elyra-ai/canvas#2236]
Ref: 15596

**Problem Description (screenshots)**

 Wrong text size for "column bounds" should be` body-short-01`
 Wrong text token for empty state paragraph, should be `helper-text-01`
Guidance [here](https://www.figma.com/file/dcNgeAq4a6GVzECwMj9AUK/Differential-privacy-HiFi?type=design&node-id=1775%3A34486&mode=design&t=HMcOtSaO0fQd7MiI-1):
![image](https://github.com/user-attachments/assets/e524f0f6-47a5-4621-9e97-cb388138799a)

**Comment by matthoward366** [comment]
This is fixed.
