### ISSUE TITLE
Close the notifications panel only when the notifications icon in the toolbar is clicked

### ISSUE THREAD

**Issue by avigadmi** [elyra-ai/canvas#25]
When notification panel is open we display more details about node errors and we don't want this info to disappear on every click. We would like to have a new config flag that will allow us to close the notifications panel only when the notifications icon in the toolbar is clicked. 

![image (9)](https://user-images.githubusercontent.com/36592011/78219813-fb806b80-74c8-11ea-95b6-59e9c8b65c37.png)

**Comment by aqtang** [comment]
This feature has been added in:
https://github.com/elyra-ai/canvas/commit/d1fb5ac6766ad72d902fb6555978d9fca6246191

There is now a boolean `keepOpen` that can be added to the `notificationConfig` object passed to `<CommonCanvas>` (which then goes to `<NotificationPanel>`), which if true will keep the notification center open until it's closed directly

**Comment by tomlyn** [comment]
Implemented in 8.0.23
