### ISSUE TITLE
Common Properties unable to render extremely large values

### ISSUE THREAD

**Issue by caritaou** [elyra-ai/canvas#333]
There is a use case where we're trying to render a list of values in a textarea control but that was crashing the browser. One of the values in the array is more than 50 million characters long. 
![image](https://user-images.githubusercontent.com/1628100/96518430-c139aa00-121f-11eb-81ca-c0671b33233d.png)
![image](https://user-images.githubusercontent.com/1628100/96518785-71a7ae00-1220-11eb-9f51-a05da26e4a4c.png)

We need to limit the length of strings getting displayed in the UI. If the value is too long, it should be displayed in a readonly mode where it cannot be edited. This applies to textarea controls standalone and in structures, as well as lists

**Comment by tomlyn** [comment]
Was this a stress test by QA or an actual user trying to do something with the data. If the latter I think we should also be trying to find out what they were trying to accomplish -- and see if we need a separate requirement.

**Comment by caritaou** [comment]
@tomlyn This was from an actual user. The data should be prepped beforehand
