### ISSUE TITLE
Port addition/deletion UI render bugs.

### ISSUE THREAD

**Issue by elewis06** [elyra-ai/canvas#357]
Two related bugs found:
-When adding a port to a node, the node height doesn't self-update. For some reason dropping a new node on to the canvas or dragging and dropping _another_ node on the canvas around seems to fix the issue.

![issue_1](https://user-images.githubusercontent.com/37430212/98974982-860b5d80-24e3-11eb-8a82-b5165ebb8a61.gif)

-When deleting an input port, a fragment of the port UI is leftover. The port no longer exists in the node's property, but the fragment lingers.

![issue_2](https://user-images.githubusercontent.com/37430212/98974986-89064e00-24e3-11eb-906a-ce0584a09fc0.gif)

**Comment by tomlyn** [comment]
I added 4 new API calls to Canvas Controller 
```
getNodeInputPorts
getNodeOutputPorts
setNodeInputPorts
setNodeOutputPorts
```
The second two need to be used to add new ports to the node; they will cause the canvas to refresh to reflect the ports specified.

**Comment by elewis06** [comment]
Second issue seems to be still persisting.
