### ISSUE TITLE
Allow for right flyout properties editor to be undocked / allow for multiple editors at once

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/canvas#379]
Having multiple properties editors open at once could be useful for users (for example, to use one node's property as a guide for another node). It'd also be useful to be able to move the properties editor wherever the user wants it to be within the canvas. Proposed feature: allowing users to "undock" the right flyout properties editor and move / resize it anywhere on the canvas.

**Comment by caritaou** [comment]
Hi @marthacryan, common-properties does have support for displaying multiple editors at the same time. This is managed by the consuming application on where to show the editors. There is an example of multiple property editors displaying on the same page in the properties documentation page (accessible by running the test harness and navigating to http://localhost:3001/#/properties)

In terms of undocking the right flyout, the right flyout panel that comes default as part of common-canvas offers an easy way for applications to get started. Applications have the ability to create their own container to display the properties editor. 
@matthoward366 Is this something that we want to offer as another option?

**Comment by tomlyn** [comment]
This is not a requirement from  any of the host apps or from product management or design - closing
