### ISSUE TITLE
Wrong package name references in Wiki

### ISSUE THREAD

**Issue by queeniema** [elyra-ai/canvas#39]
Some of the Wiki pages use the wrong [npm package](https://www.npmjs.com/package/@elyra/canvas) name in code snippets. Example: https://github.com/elyra-ai/canvas/wiki/2.0-Common-Canvas-Documentation#step-1--import

```js
    import { CommonCanvas, CanvasController } from "@elyra-ai/canvas";
```
should be:
```js
    import { CommonCanvas, CanvasController } from "@elyra/canvas";
```

**Comment by tomlyn** [comment]
@queeniema Hi Queenie - Thanks for opening this. I was thrown by the fact that the repo is in `elyra-ai` and the NPM module is in `elyra`.  I've fixed the docs. You win the prize for the first person to open an issue on the new documentation. Your prize is a free copy of elyra/canvas :)
