### ISSUE TITLE
Improve Common Properties TitleEditor

### ISSUE THREAD

**Issue by aqtang** [elyra-ai/canvas#419]
Updated design for the title component of Common Properties RHS flyouts, with support for an optional icon/label.

![image](https://user-images.githubusercontent.com/10677021/101705080-0b2e5780-3a3b-11eb-9db8-b2a293c3ab6f.png)

The edit icon should sit next to the title instead of at the end on the right. Editing the title should cause the edit icon to disappear, and editing should end on loss of focus.

**Comment by quarryboy** [comment]
@aqtang is it safe to assume we will have truncation made available for when the title is too long?

**Comment by aqtang** [comment]
@quarryboy Yes, we'll want that behavior

**Comment by aqtang** [comment]
![image](https://user-images.githubusercontent.com/10677021/102150177-d0eefc80-3e24-11eb-95be-fa5fc4962960.png)
