### ISSUE TITLE
'enum_filter' not working for 'multiselect' control

### ISSUE THREAD

**Issue by caritaou** [elyra-ai/canvas#510]
The UI does not update correctly when using an `enum_filter` condition on a `multiselect` control. 
[EnumFilterMultiselect.json.zip](https://github.com/elyra-ai/canvas/files/6045199/EnumFilterMultiselect.json.zip)

<img width="992" alt="1 multiselect - initial" src="https://media.github.ibm.com/user/11632/files/67533800-5ff7-11eb-8eef-2ca06d8e8c82">
<img width="314" alt="2 multiselect - initial options" src="https://media.github.ibm.com/user/11632/files/67ebce80-5ff7-11eb-9fe5-f1e5f22289b8">
<img width="995" alt="3 multiselect - set new options" src="https://media.github.ibm.com/user/11632/files/67ebce80-5ff7-11eb-9752-3fdc417e516c">
<img width="316" alt="4 multiselect - new options" src="https://media.github.ibm.com/user/11632/files/68846500-5ff7-11eb-9805-cb4099a6c69b">
<img width="991" alt="5 multiselect - reset to initial options" src="https://media.github.ibm.com/user/11632/files/691cfb80-5ff7-11eb-81aa-2471200f97ad">
From the above image, we can see that there are no selected options passed into the Multiselect control, but there are still items shown as selected:
<img width="313" alt="6 multiselect - option shown selected even though it shouldnt be" src="https://media.github.ibm.com/user/11632/files/6a4e2880-5ff7-11eb-9296-970c469b4d2e">

`enum_filter` is a condition option inside common properties that allows a dropdown list to have its values changed/filtered based on the value of another control. For example in the image above, the default dropdown will show all the values (red, orange, yellow, green, blue, purple). If the user selects the checkbox, the dropdown values will then be filtered to show only a subset of the original list, say red, blue, green. This is currently working for a normal dropdown

The issue is with the Carbon Combobox where users have the ability to select multiple items from the dropdown. If there is an `enum_filter` applied to this Combobox, we are not able to filter the list of original values correctly for all the different scenarios.

- if there were any preselected values before filter, the new filtered list should remove that selection - this does not work with Combobox
- if there is a default value tied to this dropdown, we need to display that as automatically selected - this does not work with Combobox
- if user makes any new selection in the filtered list and then the filter is removed, the number in the Combox does not get updated

There might be a few other cases that I dont recall with this not working, and its because of Combobox not allowing us to specify selected items, or clear selected items programmatically

**Comment by matthoward366** [comment]
A "fix" has been added for this.  carbon doesn't fully support this but a workaround was added.
