### ISSUE TITLE
Strange link decorator position for straight links with Elbow linkType

### ISSUE THREAD

**Issue by a8f** [elyra-ai/canvas#632]
Set `enableLinkType: "Elbow"` in config and add a link decorator with `position: "middle"`. It seems ok for links with a very pronounced elbow. (Also note in these screenshots the decorator svg is off-center, please ignore that 🙂 ).

![image](https://user-images.githubusercontent.com/9062366/115055160-1bee4e80-9eaf-11eb-88ed-e2e4acf1f35e.png)
However, if the elbow is very small (i.e. link is (almost) a straight line) the link decorator isn't in the middle:
![image](https://user-images.githubusercontent.com/9062366/115055191-2c062e00-9eaf-11eb-9ca0-d143ec1f9fbc.png)
![image](https://user-images.githubusercontent.com/9062366/115055253-3f18fe00-9eaf-11eb-8065-e28eee147a01.png)
I would expect that setting position middle should put the decorator in the at the midpoint of the link. If this is not the case then maybe another option can be added to force the decorator to the middle for elbow links?

**Comment by tomlyn** [comment]
Are you saying you want the position of the decorator to jump from where it is, based on the elbow, to a middle position half way between the start and end of the line when the line is **exactly** straight. What is it were just one pixel off being straight?
