### ISSUE TITLE
VPE: Enable long category names to be displayed in palette

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/canvas#779]
**Is your feature request related to a problem? Please describe.**

Component category names don't necessarily fit into the fixed space provided by the palette, leading to truncation:

![image](https://user-images.githubusercontent.com/13068832/133584415-e7967150-0a03-4647-bfec-30560b662356.png)

Currently one has to hover over a category name to read the complete text.

**Describe the solution you'd like**
 Mirror the behavior of the properties panel, which can be resized.

**Comment by ptitzler** [comment]
Is resizing of the palette something the canvas could support natively? (The capability to resize the properties panel shown in the screen capture above was added _to the Elyra pipeline editor_, but we are trying to avoid the need to reimplement the palette panel to accomplish the same.)

**Comment by tomlyn** [comment]
Yes, it is possible however it seems like a lot of work to just get some text to display. In the nodes in the palette we wrap the text. Would it work for you to do the same in the category text? Alternatively what about if we allowed you to set a different width for the palette? 

<img width="265" alt="image" src="https://user-images.githubusercontent.com/15114439/134542759-10b61aa2-4697-4744-976e-35fbb60070f0.png">

If neither of these are acceptable it would be great if you could work on the feature in Elyra Canvas and contribute it back. (It would have been useful if that could have been done with the right flyout too.)

**Comment by tomlyn** [comment]
@ptitzler   ⬆️

**Comment by ptitzler** [comment]
Yes, sorry Craig. I would probably favor the text wrapping approach, even though that might potentially yield (visually) awkward results for very long category names.

**Comment by tomlyn** [comment]
@ptitzler What size names are you using?  Why are they so long ?

**Comment by ptitzler** [comment]
Most category names are provided by the user when they add components to the registry, which populates the palette:
![image](https://user-images.githubusercontent.com/13068832/134968252-1998dfff-c370-4e6c-ad06-d09cf186996a.png)

For the "defaults" Elyra provides (see highlights) the current width is just fine:

![image](https://user-images.githubusercontent.com/13068832/134968492-fde754c9-ad58-44b8-9ff6-6e53e3c9d80a.png)

**Comment by tomlyn** [comment]
How about restrictig the number of characters they can enter for a category name?  It doesn't make sense to have really long string for what is essentially a tab title.

**Comment by ptitzler** [comment]
> How about restricting the number of characters they can enter for a category name? It doesn't make sense to have a really long string for what is essentially a tab title.

In our upcoming release we are imposing a temporary limit of 18 characters but would increase it a bit if word wrapping is supported. (18 chars appears to be the max that would fit the current dimensions of the palette based on @kiersten-stokes's testing)
