### ISSUE TITLE
Expose functionality for retrieving a list of upstream nodes

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/canvas#783]
The Canvas Controller API currently exposes branch highlight methods: 
- `highlightBranch(nodeIds, pipelineId)`
- `highlightUpstream(nodeIds, pipelineId)`
- `highlightDownstream(nodeIds, pipelineId)`

Elyra has a new usecase that requires us to retrieve a list of all upstream nodes for a given node. It would be extremely useful to have the logic that backs the branch highlight methods also exposed via the Canvas Controller API. Something like this, that returns the list of nodes/node ids:
- `getBranchNodes(nodeIds, pipelineId)`
- `getUpstreamNodes(nodeIds, pipelineId)`
- `getDownstreamNodes(nodeIds, pipelineId)`

**Comment by bourdakos1** [comment]
I just noticed that the branch highlight methods return the list of object IDs. It would be good have this functionality without the style updates 

https://github.com/elyra-ai/canvas/blob/48781597c137c4d5fc4222e5f19c1be87afca5f0/canvas_modules/common-canvas/src/common-canvas/canvas-controller.js#L1271

**Comment by tomlyn** [comment]
This change will be in the next release.

**Comment by bourdakos1** [comment]
Awesome, thank you 😁
