### ISSUE TITLE
Enable long category names to be displayed in palette

### ISSUE THREAD

**Issue by nabilIbm** [elyra-ai/canvas#817]
Currently long node names in the palette are wrapped onto a second line however category names are not

![image](https://user-images.githubusercontent.com/89609176/137775152-ea6bf452-13de-4ae0-852a-a28fb505ee60.png)
The CSS for category names should be changed to allow long category names to wrap.

Elyra Canvas issue: https://github.com/elyra-ai/canvas/issues/779

**Comment by tomlyn** [comment]
@nabilIbm   There is already an Elyra Canvas issue for this problem. #779.  Closing this one.
