### ISSUE TITLE
References and links to "wdp-pipeline-schemas" repo and internal github

### ISSUE THREAD

**Issue by guychris** [elyra-ai/canvas#97]
While browsing the wiki I found references to "wdp-pipeline-schemas" repository in a few different places and some links that give a 404, I believe this should now be referring to the elyra-ai/pipeline-schemas repo.

test harness source:
- https://github.com/elyra-ai/canvas/blob/master/canvas_modules/harness/src/client/components/common-properties-conditions.jsx#L284-L286

canvas controller source:
- https://github.com/elyra-ai/canvas/blob/master/canvas_modules/common-canvas/src/common-canvas/canvas-controller.js#L216 , and lines 228, 334, 364, 381

references to github.ibm.com in source files: https://github.com/elyra-ai/canvas/search?q=%22github.ibm.com%22&unscoped_q=%22github.ibm.com%22

And in the wiki at these pages:

- https://github.com/elyra-ai/canvas/wiki/2.0-Common-Canvas-Documentation#step-3--set-the-model-and-palette-data

- https://github.com/elyra-ai/canvas/wiki/2.4-Canvas-Controller-API#pipeline-flow-methods and "Palette methods" section

- links in this section https://github.com/elyra-ai/canvas/wiki/3.0-Common-Properties-documentation#helpclickhandler
- https://github.com/elyra-ai/canvas/wiki/3.6-Common-Properties-Controller#datasetmetadata-methods

**Comment by tomlyn** [comment]
Thanks for reporting these issues.  I fixed everything now. Let us know if you spot anything else. Thanks!
